# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8406e04c6b4ffa207d253a829aade5b345c154b6c4791223554e85cda985b72f6534b30db89dca7a32e93b2aee4ce7629e2a622d2281bdce0d4a1dea82e8df95

test:
  secret_key_base: 7b5e21a2bc3b476f3c93187da40fbbdf0270590e5509f242b56a4d4ae6d5ec3ed73bd7cd6716707e5274a3dd586915cfc975c63d8bbe2a29d1c1aeffdc8917eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
